---
# Project information
site_name: "miguelangel-nubla Home Assistant Add-ons"
site_url: "https://github.com/miguelangel-nubla/hassio-repository"
site_description: ""
site_author: "Miguel Angel Nubla"
copyright: "Copyright 2023 - Miguel Angel Nubla.Copyright 2017-2020 - Franck Nijhof."

# Repository
repo_name: "hassio-addons"
repo_url: "https://github.com/hassio-addons/repository"
edit_uri: ""

# Theme configuration
theme:
  name: "material"
  logo: "https://avatars3.githubusercontent.com/u/30772201?s=200&v=4"
  language: "en"
  palette:
    primary: "light-blue"
    accent: "blue"
  font:
    text: "Exo2"
    code: "Roboto Mono"
  feature:
    - tabs
extra_css:
  - css/extra.css

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/miguelangel-nubla/hassio-repository"

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# The pages to serve
nav:
  - "My Add-ons": "index.md"
  - "Contributing": "contributing.md"
  - "Code of Conduct": "code-of-conduct.md"
  - "License": "license.md"
